turbot/flowpipe-mod-aws

pipelines/lambda/tests/test_get_lambda_function.fp
pipelines/s3/tests/test_put_s3_bucket_versioning.fp

Add missing test tag

---

pipelines/route53/delete_route53_health_check.fp
pipelines/route53/update_route53_record.fp

Add route53 pipelines

---

pipelines/rds/delete_rds_db_instance.fp
pipelines/rds/modify_rds_db_instance.fp

Add pipeline delete_rds_db_instance and update pipeline modify_rds_db_instance

---

pipelines/vpc/delete_nat_gateway.fp
pipelines/vpc/release_eip.fp

Add pipelines release_eip and delete_nat_gateway

---

pipelines/ebs/detach_ebs_volume.fp
pipelines/ebs/modify_ebs_volume.fp

Add pipeline detach_ebs_volume and update pipeline modify_ebs_volume

---

pipelines/ebs/delete_ebs_volume.fp

Add pipeline delete_ebs_volume

---

pipelines/emr/terminate_emr_clusters.fp

Add terminate_emr_clusters pipeline

---

pipelines/ebs/delete_ebs_volume.fp
pipelines/ebs/detach_ebs_volume.fp
pipelines/ebs/modify_ebs_volume.fp
pipelines/eks/delete_eks_node_group.fp
pipelines/elasticache/delete_elasticache_cluster.fp
pipelines/elb/delete_elbv2_load_balancer.fp
pipelines/rds/delete_rds_db_instance.fp
pipelines/rds/modify_rds_db_instance.fp
pipelines/route53/delete_route53_health_check.fp
pipelines/route53/update_route53_record.fp
pipelines/secretsmanager/delete_secretsmanager_secret.fp
pipelines/vpc/delete_nat_gateway.fp
pipelines/vpc/release_eip.fp

Add pipelines for thrifty(#33)

---

pipelines/s3/put_s3_bucket_lifecycle_policy.fp

Add pipeline put_s3_bucket_lifecycle_policy

---

pipelines/dynamodb/delete_dynamodb_table.fp

Add pipeline delete_dynamodb_table

---

pipelines/ebs/modify_ebs_snapshot.fp

Add modify_ebs_snapshot pipeline

---

pipelines/dynamodb/update_dynamodb_table.fp

Add pipeline update_dynamodb_table

---

pipelines/dynamodb/update_dynamodb_continuous_backup.fp

Add pipeline update_dynamodb_continuous_backup

---

pipelines/elb/modify_elb_attributes.fp

Add modify_elb_attributes pipeline

---

pipelines/rds/modify_rds_db_instance.fp

Update modify_rds_db_instance pipeline to include copy_tags_to_snapshot option

---

pipelines/rds/modify_rds_db_instance.fp

Update modify_rds_db_instance pipeline to include auto_minor_version_upgrade, iam_database_authentication and multi_az options

---

pipelines/ec2/detach_network_interface.fp

Add detach_network_interface pipeline

---

pipelines/iam/update_iam_account_password_policy.fp

Add IAM update password policy pipeline

---

pipelines/cloudwatch/create_cloudwatch_log_group.fp
pipelines/cloudwatch/create_cloudwatch_log_stream.fp
pipelines/ec2/modify_client_vpn_endpoint.fp

Add create_cloudwatch_log_group, create_cloudwatch_log_stream and modify_client_vpn_endpoint pipelines

---

pipelines/vpc/delete_network_acl_entry.fp

Add delete_network_acl_entry pipeline

---

pipelines/vpc/create_vpc_flow_logs.fp

Add create_vpc_flow_logs pipeline

---

pipelines/kms/put_key_policy.fp

Add pipeline kms_key_put_policy 

---

pipelines/s3/put_s3_bucket_policy.fp
pipelines/vpc/delete_network_acl_entry.fp

Add pipeline put_s3_bucket_policy

---

pipelines/account/put_alternate_contact.fp

Add pipeline put_alternate_contact

---

pipelines/iam/change_iam_password.fp
pipelines/iam/delete_iam_server_certificate.fp
pipelines/neptune/modify_neptune_db_cluster.fp

Add new pipelines

---

pipelines/vpc/revoke_vpc_security_group_egress.fp

Add revoke_vpc_security_group_egress pipeline

---

pipelines/iam/update_iam_account_password_policy.fp

Update update_iam_account_password_policy pipeline

---

pipelines/iam/delete_iam_access_analyzer.fp
pipelines/iam/detach_iam_group_policy.fp
pipelines/iam/detach_iam_role_policy.fp
pipelines/iam/detach_iam_user_policy.fp

Add detach_iam_group_policy, detach_iam_role_policy and delete_iam_access_analyzer pipelines

---

pipelines/iam/generate_iam_credential_report.fp

Add generate_iam_credential_report pipeline
